import {
  ArrowLeft,
  ChevronRight,
  User,
  Phone,
  Mail,
  MapPin,
  Calendar,
  Clock,
  Users,
  Skull,
  Eye,
  Shield,
  Zap,
  Tag,
  CheckCircle,
  Gamepad2,
} from "lucide-react";
export const ALL_EVENTS = [
  {
    id: "social-deduction-apr1",
    title: "Social Deduction Night",
    subtitle:
      "Mafia Vendetta · Secret Hitler · One Night Ultimate Werewolf · Coup",
    date: "Tuesday, April 1st 2026",
    isoDate: "2026-04-01T16:00:00",
    time: "4:00 PM onwards",
    venue: "Melons Studio, Lucknow",
    fee: 100,
    originalFee: 200,
    spotsLeft: 20,
    attendees: 18,
    tags: ["Board Games", "Social Deduction"],
    icon: <Skull className="w-6 h-6" />,
    accentBorder: "border-red-500/40 hover:border-red-400/70",
    selectedBorder: "border-primary ring-2 ring-primary/30",
    gradientStrip: "from-red-700 to-primary",
    badge: "bg-red-500/20 text-red-300 border-red-500/30",
    games: [
      { name: "Mafia Vendetta", icon: <Skull className="w-4 h-4" /> },
      { name: "Secret Hitler", icon: <Eye className="w-4 h-4" /> },
      {
        name: "One Night Ultimate Werewolf",
        icon: <Shield className="w-4 h-4" />,
      },
      { name: "Coup", icon: <Zap className="w-4 h-4" /> },
    ],
    description:
      "An evening of bluffing, betrayal and social deduction. Multiple rounds of the best hidden-role games with fellow gamers. Beginners welcome!",
    upi: "8400224215@pthdfc",
    whatsapp: "918400224215",
    open: false,
  },
  {
    id: "social-deduction-apr7",
    title: "Social Deduction Night",
    subtitle:
      "Mafia Vendetta · Secret Hitler · One Night Ultimate Werewolf · Coup",
    date: "Tuesday, April 7th 2026",
    isoDate: "2026-04-07T16:00:00",
    time: "4:00 PM onwards",
    venue: "Melons Studio, Lucknow",
    fee: 100,
    originalFee: 200,
    spotsLeft: 20,
    attendees: 0,
    tags: ["Board Games", "Social Deduction"],
    icon: <Skull className="w-6 h-6" />,
    accentBorder: "border-red-500/40 hover:border-red-400/70",
    selectedBorder: "border-primary ring-2 ring-primary/30",
    gradientStrip: "from-red-700 to-primary",
    badge: "bg-red-500/20 text-red-300 border-red-500/30",
    games: [
      { name: "Mafia Vendetta", icon: <Skull className="w-4 h-4" /> },
      { name: "Secret Hitler", icon: <Eye className="w-4 h-4" /> },
      {
        name: "One Night Ultimate Werewolf",
        icon: <Shield className="w-4 h-4" />,
      },
      { name: "Coup", icon: <Zap className="w-4 h-4" /> },
    ],
    description:
      "An evening of bluffing, betrayal and social deduction. Multiple rounds of the best hidden-role games with fellow gamers. Beginners welcome!",
    upi: "8400224215@pthdfc",
    whatsapp: "918400224215",
    open: false, // ← moved to past
  },
  {
    id: "board-game-bonanza-apr11",
    title: "Board Game Bonanza",
    subtitle:
      "Catan · Azul · Cluedo GoT · Exploding Kittens · Kingdomino · Ticket to Ride · Shasn · Forbidden Desert · Scotland Yard · Uno No Mercy",
    date: "Friday, April 10th 2026",
    isoDate: "2026-04-10T16:00:00",
    time: "4:00 PM onwards",
    venue: "Melons Studio, Lucknow",
    fee: 100,
    originalFee: 200,
    spotsLeft: 20,
    attendees: 0,
    tags: ["Board Games", "Collab Event"],
    icon: <Gamepad2 className="w-6 h-6" />,
    accentBorder: "border-amber-500/40 hover:border-amber-400/70",
    selectedBorder: "border-primary ring-2 ring-primary/30",
    gradientStrip: "from-amber-600 to-primary",
    badge: "bg-amber-500/20 text-amber-300 border-amber-500/30",
    games: [
      { name: "Catan", icon: <Gamepad2 className="w-4 h-4" /> },
      { name: "Azul", icon: <Gamepad2 className="w-4 h-4" /> },
      {
        name: "Cluedo: Game of Thrones",
        icon: <Gamepad2 className="w-4 h-4" />,
      },
      {
        name: "Exploding Kittens Party",
        icon: <Gamepad2 className="w-4 h-4" />,
      },
      { name: "Kingdomino", icon: <Gamepad2 className="w-4 h-4" /> },
      { name: "Ticket to Ride", icon: <Gamepad2 className="w-4 h-4" /> },
      { name: "Shasn", icon: <Gamepad2 className="w-4 h-4" /> },
      { name: "Forbidden Desert", icon: <Gamepad2 className="w-4 h-4" /> },
      { name: "Scotland Yard", icon: <Gamepad2 className="w-4 h-4" /> },
      { name: "Uno No Mercy", icon: <Gamepad2 className="w-4 h-4" /> },
    ],
    description:
      "A massive board game night in collaboration with Melons Studio! From strategy to co-op to party games — 10 titles across all genres. Beginners absolutely welcome, taught games available all evening.",
    collaborator: "Melons Studio",
    upi: "8400224215@pthdfc",
    whatsapp: "918400224215",
    open: false,
  },
  {
    id: "social-deduction-apr7",
    title: "Social Deduction Night",
    subtitle:
      "Mafia Vendetta · Secret Hitler · One Night Ultimate Werewolf · Coup",
    date: "Tuesday, April 14th 2026",
    isoDate: "2026-04-14T16:00:00",
    time: "4:00 PM onwards",
    venue: "Melons Studio, Lucknow",
    fee: 100,
    originalFee: 200,
    spotsLeft: 20,
    attendees: 0,
    tags: ["Board Games", "Social Deduction"],
    icon: <Skull className="w-6 h-6" />,
    accentBorder: "border-red-500/40 hover:border-red-400/70",
    selectedBorder: "border-primary ring-2 ring-primary/30",
    gradientStrip: "from-red-700 to-primary",
    badge: "bg-red-500/20 text-red-300 border-red-500/30",
    games: [
      { name: "Mafia Vendetta", icon: <Skull className="w-4 h-4" /> },
      { name: "Secret Hitler", icon: <Eye className="w-4 h-4" /> },
      {
        name: "One Night Ultimate Werewolf",
        icon: <Shield className="w-4 h-4" />,
      },
      { name: "Coup", icon: <Zap className="w-4 h-4" /> },
    ],
    description:
      "An evening of bluffing, betrayal and social deduction. Multiple rounds of the best hidden-role games with fellow gamers. Beginners welcome!",
    upi: "8400224215@pthdfc",
    whatsapp: "918400224215",
    open: false,
  },
  {
    id: "board-game-bonanza-apr11",
    title: "Board Game Bonanza",
    subtitle:
      "Catan · Azul · Cluedo GoT · Exploding Kittens · Kingdomino · Ticket to Ride · Shasn · Forbidden Desert · Scotland Yard · Uno No Mercy",
    date: "Friday, April 17th 2026",
    isoDate: "2026-04-17T16:00:00",
    time: "4:00 PM onwards",
    venue: "Melons Studio, Lucknow",
    fee: 100,
    originalFee: 200,
    spotsLeft: 20,
    attendees: 0,
    tags: ["Board Games", "Collab Event"],
    icon: <Gamepad2 className="w-6 h-6" />,
    accentBorder: "border-amber-500/40 hover:border-amber-400/70",
    selectedBorder: "border-primary ring-2 ring-primary/30",
    gradientStrip: "from-amber-600 to-primary",
    badge: "bg-amber-500/20 text-amber-300 border-amber-500/30",
    games: [
      { name: "Catan", icon: <Gamepad2 className="w-4 h-4" /> },
      { name: "Azul", icon: <Gamepad2 className="w-4 h-4" /> },
      {
        name: "Cluedo: Game of Thrones",
        icon: <Gamepad2 className="w-4 h-4" />,
      },
      {
        name: "Exploding Kittens Party",
        icon: <Gamepad2 className="w-4 h-4" />,
      },
      { name: "Kingdomino", icon: <Gamepad2 className="w-4 h-4" /> },
      { name: "Ticket to Ride", icon: <Gamepad2 className="w-4 h-4" /> },
      { name: "Shasn", icon: <Gamepad2 className="w-4 h-4" /> },
      { name: "Forbidden Desert", icon: <Gamepad2 className="w-4 h-4" /> },
      { name: "Scotland Yard", icon: <Gamepad2 className="w-4 h-4" /> },
      { name: "Uno No Mercy", icon: <Gamepad2 className="w-4 h-4" /> },
    ],
    description:
      "A massive board game night in collaboration with Melons Studio! From strategy to co-op to party games — 10 titles across all genres. Beginners absolutely welcome, taught games available all evening.",
    collaborator: "Melons Studio",
    upi: "8400224215@pthdfc",
    whatsapp: "918400224215",
    open: false,
  },
  {
    id: "social-deduction-apr7",
    title: "Social Deduction Night",
    subtitle:
      "Mafia Vendetta · Secret Hitler · One Night Ultimate Werewolf · Coup",
    date: "Tuesday, April 21st 2026",
    isoDate: "2026-04-21T16:00:00",
    time: "4:00 PM onwards",
    venue: "Melons Studio, Lucknow",
    fee: 100,
    originalFee: 200,
    spotsLeft: 20,
    attendees: 0,
    tags: ["Board Games", "Social Deduction"],
    icon: <Skull className="w-6 h-6" />,
    accentBorder: "border-red-500/40 hover:border-red-400/70",
    selectedBorder: "border-primary ring-2 ring-primary/30",
    gradientStrip: "from-red-700 to-primary",
    badge: "bg-red-500/20 text-red-300 border-red-500/30",
    games: [
      { name: "Mafia Vendetta", icon: <Skull className="w-4 h-4" /> },
      { name: "Secret Hitler", icon: <Eye className="w-4 h-4" /> },
      {
        name: "One Night Ultimate Werewolf",
        icon: <Shield className="w-4 h-4" />,
      },
      { name: "Coup", icon: <Zap className="w-4 h-4" /> },
    ],
    description:
      "An evening of bluffing, betrayal and social deduction. Multiple rounds of the best hidden-role games with fellow gamers. Beginners welcome!",
    upi: "8400224215@pthdfc",
    whatsapp: "918400224215",
    open: false,
  },
   {
    id: "board-game-bonanza-apr11",
    title: "Board Game Bonanza",
    subtitle:
      "Catan · Azul · Cluedo GoT · Exploding Kittens · Kingdomino · Ticket to Ride · Shasn · Forbidden Desert · Scotland Yard · Uno No Mercy",
    date: "Tuesday, April 29th 2026",
    isoDate: "2026-04-29T16:00:00",
    time: "4:00 PM onwards",
    venue: "Art Station Studio, Lucknow",
    fee: 100,
    originalFee: 200,
    spotsLeft: 20,
    attendees: 0,
    tags: ["Board Games", "Collab Event"],
    icon: <Gamepad2 className="w-6 h-6" />,
    accentBorder: "border-amber-500/40 hover:border-amber-400/70",
    selectedBorder: "border-primary ring-2 ring-primary/30",
    gradientStrip: "from-amber-600 to-primary",
    badge: "bg-amber-500/20 text-amber-300 border-amber-500/30",
    games: [
      { name: "Catan", icon: <Gamepad2 className="w-4 h-4" /> },
      { name: "Azul", icon: <Gamepad2 className="w-4 h-4" /> },
      {
        name: "Cluedo: Game of Thrones",
        icon: <Gamepad2 className="w-4 h-4" />,
      },
      {
        name: "Exploding Kittens Party",
        icon: <Gamepad2 className="w-4 h-4" />,
      },
      { name: "Kingdomino", icon: <Gamepad2 className="w-4 h-4" /> },
      { name: "Ticket to Ride", icon: <Gamepad2 className="w-4 h-4" /> },
      { name: "Shasn", icon: <Gamepad2 className="w-4 h-4" /> },
      { name: "Forbidden Desert", icon: <Gamepad2 className="w-4 h-4" /> },
      { name: "Scotland Yard", icon: <Gamepad2 className="w-4 h-4" /> },
      { name: "Uno No Mercy", icon: <Gamepad2 className="w-4 h-4" /> },
    ],
    description:
      "A massive board game night in collaboration with Melons Studio! From strategy to co-op to party games — 10 titles across all genres. Beginners absolutely welcome, taught games available all evening.",
    collaborator: "Melons Studio",
    upi: "8400224215@pthdfc",
    whatsapp: "918400224215",
    open: true,
  },
];
